conf.py:
  copyright: 2006-2016
  project: TC Tools - Backend User administration module
  version: 3.0
  release: 3.0.0
  latex_documents:
  - - Index
    - tc_beuser.tex
    - TC Tools Backend user administration
    - Ivan Kartolo
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}